### ISSUE TITLE
Example pipeline err - DSL - Control structures

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical/kfp-operators#10]
![Screenshot from 2021-05-26 17-48-51](https://user-images.githubusercontent.com/27001378/119700011-a8931180-be4a-11eb-92eb-6a43033c7b8b.png)

**Comment by knkski** [comment]
This is actually as expected. This pipeline is an example of both conditional pipeline steps and steps that run even if a previous step failed. In other words, sometimes the pipeline will run the `Fail op` step and sometimes it won't, but it will always run the `Print op`, even if the overall pipeline failed due to running the `Fail op`. See here for more info:

https://github.com/kubeflow/pipelines/blob/cc83e108/samples/tutorials/DSL%20-%20Control%20structures/DSL%20-%20Control%20structures.py#L117-L118
